### ISSUE TITLE
Error:"Could not setup macOS environment, error: exit status 1" in the Flutter step v0.0.8.

### ISSUE THREAD

**Issue by yumatan** [DroidsOnRoids/bitrise-step-flutter#14]
I have been faced with the following problem in the Flutter step v0.0.8.

I check the case that it succeeded on December 13,2019(GMT+0900) and failed on December 16,2019(GMT+0900).

```
■Log excerpt(Failure patern)

Accept? (y/N): All SDK package licenses accepted

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named six
[34;1msix Python module not found, installing it with easy_install...[0m
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Searching for six
Reading https://pypi.org/simple/six/
Download error on https://pypi.org/simple/six/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'six' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for six
error: Could not find suitable distribution for Requirement.parse('six')
[31;1mCould not setup macOS environment, error: exit status 1[0m
```

 and

```
■Log excerpt(Success patern)

Accept? (y/N): All SDK package licenses accepted

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named six
[34;1msix Python module not found, installing it with easy_install...[0m
Searching for six
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl#sha256=1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd
Best match: six 1.13.0
Processing six-1.13.0-py2.py3-none-any.whl
Installing six-1.13.0-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding six 1.13.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/six-1.13.0-py2.7.egg
Processing dependencies for six
Finished processing dependencies for six
[34;1mExtracting Flutter SDK to /Users/vagrant/Library/flutter[0m
[34;1mVersion stable not found in releases, trying snapshot.[0m
[34;1mExecuting Flutter command: build ios --release --flavor dev --target lib/main_dev.dart --build-number=XXXX[0m
Downloading Dart SDK from Flutter engine 2994f7e1e682039464cb25e31a78b86a3c59b695...
```

The former differs from the latter in that it cannot download "https://pypi.org/simple/six/" .

```
Reading https://pypi.org/simple/six/
Download error on https://pypi.org/simple/six/: unknown url type: https -- Some packages may not be found!
```
Does anyone face the same problem?

Thank you,

**Comment by koral--** [comment]
Which stack are you using?

**Comment by yumatan** [comment]
![Bitrise Stack](https://user-images.githubusercontent.com/18245704/70987055-80a26900-2102-11ea-8587-c94414d3d991.png)

The workflow which contains "Flutter v0.0.8" had rarely succeeded with Xcode 11.1.x, on macOS 10.14.6(Mojave).

However, we found that **it always succeeds with Xcode 11.3.x, on macOS 10.14.6(Mojave).**

Is there anything that comes to mind as to what may have caused this?

Is it recommended that we always use the latest stack for building Flutter application with this step?

Thank you,

**Comment by koral--** [comment]
It is recommended to use the latest possible stack which can support your workflow.
This issue is caused by OpenSSL update: https://github.com/bitrise-io/bitrise.io/pull/329#issuecomment-565508601

I'll try to continue support this stack.

**Comment by yumatan** [comment]
Thank you for your reply and information.

We will try to support the latest Xcode regarding our flutter applications.

Thank you.
