### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ltropin** [DroidsOnRoids/bitrise-step-flutter#20]
When i run step **flutter doctor** i get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Could not setup Android SDK, error: exit status 1
```

My configuration:

Flutter version: stable
Root directory of Flutter project: $BITRISE_SOURCE_DIR
Flutter commands to be executed: doctor

**Comment by koral--** [comment]
It is a consequence of java version change on the stack: https://discuss.bitrise.io/t/weekly-virtual-machine-stack-updates-2021-09-14/17982, not a step issue.
You can do one of the following things:
* set java version in your build to one desired by Android commadline tools, in this case probably downgrade to 8. See how to do it here: https://devcenter.bitrise.io/infrastructure/virtual-machines/#managing-java-versions
* update Android commadline tools to version compatible with java on your stack
* use a different stack where versions of those component match

**Comment by koral--** [comment]
Sounds good, will check that!

**Comment by johsoe** [comment]
This should work https://github.com/DroidsOnRoids/bitrise-step-flutter/pull/21

**Comment by moatazeldebsy** [comment]
Hello any updates about this issue, it's not `doctor` command only, any command that occurred the same issue
<img width="926" alt="Screenshot 2021-11-26 at 01 01 33" src="https://user-images.githubusercontent.com/45570191/143585250-e7e9feef-759b-43aa-9728-11deae8349d5.png">

**Comment by koral--** [comment]
Fix for that was proposed by @Miiha in #21 but the CI build failed.
Let's give @Miiha a week from now to react. In case of no reaction I'll take care of that myself.

**Comment by Miiha** [comment]
@koral-- would be great if you will look into it.

**Comment by koral--** [comment]
OK, will do that.
